---
- name: Gather facts
  hosts: all
  gather_facts: yes

- hosts: microd0s
  roles:
    - common
    - guibox
    - laptop
    - devbox
    - haskell
    - dell-xps-9370

- hosts: wr4ith
  roles:
    - common
    - guibox
    - laptop
    - devbox
    - asus-n550
