---
- name: Gather facts
  hosts: all
  gather_facts: yes

- hosts: microd0s
  roles:
    - common
    - guibox
    - laptop
    - bluetooth
    - devbox
    - haskell
    - gaming
    - android
    - dell-xps-9370
    - emacs

- hosts: 0utbreak
  roles:
    - common
    - guibox
    - laptop
    - bluetooth
    - devbox
    - haskell
