---
- name: Gather facts
  hosts: all
  gather_facts: yes

- hosts: microd0s
  roles:
    - common
    - guibox
    - laptop
    - bluetooth
    - devbox
    - haskell
    - gaming
    - android
    - hardware
    - tailscale
    - dell-xps-9370
    - role: emacs
      tags: emacs

- hosts: d1sclosure
  roles:
    - common
    - server
    - tailscale
