---
- name: Gather facts
  hosts: all
  gather_facts: yes

- hosts: h4lfwit
  roles:
    - common
    - guibox
    - laptop
    - devbox
    - haskell

- hosts: wr4ith
  roles:
    - common
    - guibox
    - laptop
    - devbox
    - asus-n550
