---
- name: Gather facts
  hosts: all
  gather_facts: yes

- hosts: microd0s
  roles:
    - common
    - guibox
    - laptop
    - devbox
    - haskell
    - gaming
    - dell-xps-9370

- hosts: 0utbreak
  roles:
    - common
    - guibox
    - laptop
    - devbox
    - haskell
