---
- name: Gather facts
  hosts: all
  gather_facts: yes

- hosts: microd0s
  roles:
    - common
    - guibox
    - laptop
    - bluetooth
    - devbox
    - haskell
    - gaming
    - android
    - fpv
    - dell-xps-9370
    - role: emacs
      tags: emacs
    - role: guix
      tags: guix

- hosts: 0utbreak
  roles:
    - common
    - guibox
    - laptop
    - bluetooth
    - devbox
    - haskell
    - emacs
    - role: emacs
      tags: emacs
    - role: guix
      tags: guix
