---
- name: Install development tools
  pacman:
    state: latest
    name:
      - git
      - docker
      - docker-compose
      - nodejs
      - npm
      - aws-cli
      - python2-virtualenv
      - lzop
      - packer

      # For running kubernetes with kvm via minikube
      - qemu-headless
      - libvirt
      - ebtables # Required for libvirt networking
      - dnsmasq # Ditto

- name: Install devtools from aur
  aur: name={{ item }} use=makepkg skip_installed=yes
  become: yes
  become_user: will
  with_items:
    - minikube
    - docker-machine-driver-kvm2
    - kubectl
    - kubectx
    - kubernetes-helm
    - jmeter
    - sops
    - kops-bin

- name: Install expo-cli
  npm:
    name: expo-cli
    global: yes
    production: yes

- name: Add myself to libvirt group
  user:
    name: will
    groups: libvirt
    append: yes

- name: Start libvirt daemon at boot time
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Install gitconfig
  copy:
    src: gitconfig
    dest: /home/will/.gitconfig
    owner: will
    group: will

- name: Start docker daemon at boot time
  systemd:
    name: docker
    enabled: yes
    state: started # Also ensure it's currently running, for good measure.

- name: Add myself to the docker group
  user:
    name: will
    groups: docker
    append: yes
...
