---
- name: Install development tools
  pacman:
    state: latest
    name:
      - git
      - docker
      - docker-compose
      - nodejs
      - npm
      - yarn
      - aws-cli
      - python2-virtualenv
      - lzop
      - packer
      - aircrack-ng
      - john
      - qemu-headless
      - libvirt
      - virt-install
      - virt-viewer
      - virt-manager
      - ovmf # Libvirt EUFI boot support
      - dnsmasq # Ditto
      - arch-install-scripts
      - minikube
      - kubectl
      - kubectx
      - kustomize
      - skaffold
      - bazel
      - code
      - rustup

- name: Install devtools from aur
  aur:
    use: makepkg
    skip_installed: yes
    name:
      - docker-machine-driver-kvm2
      - kubernetes-helm
      - jmeter
      - sops
      - kops-bin
      - ibazel
      - python-configparser
      - python-aws-google-auth
      - google-cloud-sdk
  become: yes
  become_user: "{{ user_name }}"

- name: Install expo-cli
  npm:
    name: expo-cli
    global: yes
    production: yes

- name: Add myself to libvirt group
  user:
    name: "{{ user_name }}"
    groups: libvirt
    append: yes

- name: Start libvirt daemon at boot time
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Install gitconfig
  copy:
    src: gitconfig
    dest: /home/{{ user_name }}/.gitconfig
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Install bazelrc
  copy:
    src: bazelrc
    dest: /home/{{ user_name }}/.bazelrc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Start docker daemon at boot time
  systemd:
    name: docker
    enabled: yes
    state: started # Also ensure it's currently running, for good measure.

- name: Add myself to the docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
...
