---
- name: Install development tools
  pacman: name={{ item }} state=latest
  with_items:
    - git
    - docker
    - docker-compose
    - nodejs
    - npm
    - aws-cli
    - python2-virtualenv
    - lzop
    - jmeter

- name: Install k8s tooling from aur
  aur: name={{ item }} use=makepkg skip_installed=yes
  become: yes
  become_user: will
  with_items:
    - minikube
    - kubectl
    - kubectx

- name: Install gitconfig
  copy:
    src: gitconfig
    dest: /home/will/.gitconfig
    owner: will
    group: will

- name: Start docker daemon at boot time
  systemd:
    name: docker
    enabled: yes
    state: started # Also ensure it's currently running, for good measure.

- name: Add myself to the docker group
  user:
    name: will
    groups: docker
    append: yes
...
