---
- name: Install development tools
  pacman:
    state: latest
    name:
      - git
      - docker
      - docker-compose
      - nodejs
      - npm
      - yarn
      - aws-cli
      - python2-virtualenv
      - lzop
      - packer
      - aircrack-ng
      - qemu-headless
      - libvirt
      - virt-install
      - virt-viewer
      - ovmf # Libvirt EUFI boot support
      - ebtables # Required for libvirt networking
      - dnsmasq # Ditto
      - arch-install-scripts
      - minikube
      - kubectl
      - kubectx
      - kustomize
      - skaffold
      - bazel
      - code

- name: Install devtools from aur
  aur: name={{ item }} use=makepkg skip_installed=yes
  become: yes
  become_user: will
  with_items:
    - docker-machine-driver-kvm2
    - kubernetes-helm
    - jmeter
    - sops
    - kops-bin
    - ibazel
    - python-aws-google-auth

- name: Install expo-cli
  npm:
    name: expo-cli
    global: yes
    production: yes

- name: Add myself to libvirt group
  user:
    name: will
    groups: libvirt
    append: yes

- name: Start libvirt daemon at boot time
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Install gitconfig
  copy:
    src: gitconfig
    dest: /home/will/.gitconfig
    owner: will
    group: will

- name: Start docker daemon at boot time
  systemd:
    name: docker
    enabled: yes
    state: started # Also ensure it's currently running, for good measure.

- name: Add myself to the docker group
  user:
    name: will
    groups: docker
    append: yes
...
