# Set xresources - (urxvrt, )
xrdb -merge ~/.Xresources
# Cursor
xsetroot -cursor_name left_ptr
# US Keymap everywhere (even on non-us keyboards), for consistency
setxkbmap -layout us
# Increase key repeat rate
xset r rate 200 28
# Wallpaper
feh --bg-scale ~/.wallpaper.jpg &
# Enable screen mirroring on work laptop (bit filth I know)
if [[ "$(cat /etc/hostname)" == "wr4ith" ]]; then
  xrandr --output eDP-1 --auto --output HDMI-1 --auto --same-as eDP-1 --output HDMI-2 --auto --same-as eDP-1
fi
# Xmonad
exec xmonad

