---
- name: Install android tools
  pacman:
    state: latest
    name:
      - android-tools
      - android-udev
      - aarch64-linux-gnu-gcc
      - clang

- name: Install pmbootstrap
  aur:
    use: makepkg
    state: present
    name:
      - pmbootstrap
  become: yes
  become_user: "{{ user_name }}"

- name: Add myself to adbusers group
  user:
    name: "{{ user_name }}"
    groups: adbusers
    append: yes
...
