---
- name: Install xorg server, xmonad & xmobar
  pacman: name={{ item }} state=latest
  with_items:
    - xorg-server
    - xorg-server-utils
    - xorg-xinit # TODO replace with my own startx script
    - xorg-xsetroot # For setting the default cursor
    - xorg-xprop # For querying info about open windows
    - xorg-xfontsel # For visually selecting font strings
    - xmonad
    - xmonad-contrib
    - xmobar
    - dmenu
    - feh
    - alsa-utils # So xmonad can control volume levels through amixer
    - libnotify

- name: Install xmonad config
  copy:
    src: xmonad/
    dest: /home/will/.xmonad
    owner: will
    group: will
  notify:
    - recompile xmonad

- name: Install xmobarrc
  template:
    src: xmobarrc.j2
    dest: /home/will/.xmobarrc
    owner: will
    group: will
  notify:
    - recompile xmonad

- name: Install other configuration dotfiles (/dotfolders)
  copy:
    src: "{{ item }}"
    dest: "/home/will/.{{ item }}"
    owner: will
    group: will
  with_items:
    - xinitrc
    - Xresources
    - wallpaper.jpg

- name: Install gui niceties
  pacman: name={{ item }} state=latest
  with_items:
    - rxvt-unicode
    - urxvt-perls
    - chromium
    - firefox
    - ttf-dejavu
    - scrot
    - gimp
    - transmission-gtk
    - vlc
