---
- name: Install xorg server, xmonad & xmobar
  pacman:
    state: latest
    name:
      - xorg-server
      - xorg-xinit # TODO replace with my own startx script
      - xorg-xsetroot # For setting the default cursor
      - xorg-xprop # For querying info about open windows
      - xorg-xev # For printing x server events
      - xorg-xfontsel # For visually selecting font strings
      - xorg-xrandr
      - xorg-xbacklight
      - xmonad
      - xmonad-contrib
      - xmobar
      - dmenu
      - feh
      - alsa-utils # So xmonad can control volume levels through amixer
      - libnotify
      - dunst

- name: Install xmonad config
  copy:
    src: xmonad/
    dest: /home/{{ user_name }}/.xmonad
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  notify:
    - recompile xmonad

- name: Install xmobarrc
  template:
    src: xmobarrc.j2
    dest: /home/{{ user_name }}/.xmobarrc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  notify:
    - recompile xmonad

- name: Create dunst config directory
  file:
    path: /home/{{ user_name }}/.config/dunst
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Install dunstrc
  copy:
    src: dunstrc
    dest: /home/{{ user_name }}/.config/dunst/dunstrc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Install other configuration dotfiles (/dotfolders)
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user_name }}/.{{ item }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  with_items:
    - xinitrc
    - Xresources
    - wallpaper.jpg

- name: Install gui niceties
  pacman:
    state: latest
    name:
      - rxvt-unicode
      - urxvt-perls
      - firefox
      - ttf-dejavu
      - scrot
      - gimp
      - libreoffice-still
      - transmission-gtk
      - vlc
      - freerdp

- name: Install aur packages
  aur:
    name: "{{ item }}"
    use: makepkg
    skip_installed: yes
  with_items:
    - zoom
    - google-chrome
    - urxvt-resize-font-git # For font resizing on the fly
  become: yes
  become_user: "{{ user_name }}"

- name: Install fonts for Chinese/Japanese/Korean characters
  pacman:
    state: latest
    name:
      - adobe-source-han-sans-otc-fonts # Sans
      - adobe-source-han-serif-otc-fonts # Serif

- name: Install pulseaudio
  pacman:
    state: latest
    name:
      - pulseaudio
      - pulsemixer

