---
- name: Install laptop mode tools
  aur:
    name: laptop-mode-tools
    use: makepkg
  become_user: will
  become: true

- name: Install synaptics driver
  pacman: name=xf86-input-synaptics state=latest

- name: Install touchpad config
  copy:
    src: 50-synaptics.conf
    dest: /etc/X11/xorg.conf.d/50-synaptics.conf
    owner: root
    group: root

- name: Install firmware update service
  pacman: name=fwupd state=latest
