---

- name: Install guix (if not already installed)
  shell:
    cmd: >-
      if ! which guix; then
        cd /tmp
        wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
        chmod +x guix-install.sh
        ./guix-install.sh
      fi

- name: Update/downgrade guix itself to my pinned version
  shell:
    cmd: "guix time-machine --channels={{role_path}}/files/channels.scm -- pull"

- name: Install guix home profile
  shell:
    cmd: "guix time-machine --channels={{ role_path }}/files/channels.scm -- home reconfigure {{ role_path }}/files/home.scm"
  become: yes
  become_user: "{{ user_name }}"
