---

- name: Install wget for guix install script
  pacman:
    name: wget
    state: latest

- name: Install guix (if not already installed)
  shell:
    cmd: >-
      set -ex;
      if ! which guix; then
        cd /tmp;
        wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh;
        chmod +x ./guix-install.sh;
        yes | ./guix-install.sh;
      fi

- name: Install guix home profile
  shell:
    cmd: "guix time-machine --channels={{ role_path }}/files/channels.scm -- home reconfigure {{ role_path }}/files/home.scm"
  become: yes
  become_user: "{{ user_name }}"
