---
- name: Install emacs
  pacman:
    state: latest
    name:
      - emacs
      - libvterm # For terminal emulation
      - cmake # Dependency of vterm.el

- name: Create emacs config directory
  file:
    path: /home/{{ user_name }}/.config/emacs
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Install init.el
  copy:
    src: init.el
    dest: /home/{{ user_name }}/.config/emacs/init.el
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  notify:
    - Restart emacs service

# May fail on first install, run again after logging in and executing with sudo.
- name: Enable emacs systemd user service
  systemd:
    enabled: yes
    name: emacs
    scope: user
    state: started
  become: yes
  become_user: "{{ user_name }}"

- name: Install typescript & typescript-language-server globally
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    global: yes
    production: yes
    state: present
  with_items:
    - name: typescript
      version: 4.3.4
    - name: typescript-language-server
      version: 0.6.3

- name: Install haskell-language-server
  pacman:
    name: haskell-language-server
    state: latest
  # Temporarily skip this while it gets updated
  # Upstream bugs:
  #   https://bugs.archlinux.org/task/72401
  #   https://bugs.archlinux.org/task/72456
  tags:
    - never
