" Load pathogen (plugin manager)
execute pathogen#infect()

syntax on
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2

" Sets the 'leader' key to comma since it's close
let mapleader = ","

" Highlight matching {[()]}
set showmatch

" Visual tab filename autocompletion
set wildmenu

" Dark grey line numbers
set number
hi LineNr ctermfg=darkgrey

" Highlight trailing whitspace
hi ExtraWhitespace ctermbg=darkred
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhitespace /\s\+$/

" Don't redraw so much
set lazyredraw

" Realtime search & highlighting
set incsearch
set hlsearch
" ,<space> -> stop highlighting search results.
nnoremap <leader><space> :nohlsearch<CR>

" Force latex highlighting
let g:tex_flavor = "latex"
" Spellchecking for .tex files
autocmd FileType tex setlocal spell


" Indentation
set autoindent
set smartindent
filetype on
filetype plugin on
filetype indent on
filetype plugin indent on
" Indenting inside a set of braces will add an extra-indented newline in-between
" and leave us there to carry on typing
let g:AutoPairsMapCR = 1

" Only jump over auto-created closing braces, quotes etc. insert a new one if
" the next one was created outside of the current editing session
let g:AutoPairsUseInsertedCount = 1

" Omni-completion
set omnifunc=syntaxcomplete#Complete

"" Typescript config
" Edit typescript files in-place for better webpack 'watch' compatibility
autocmd FileType typescript setlocal backupcopy=yes
autocmd FileType typescript nnoremap <leader>t :echo tsuquyomi#hint()<CR>

" Ensure that tsx files are both highlighted and type-checked properly
" See: https://github.com/Quramy/tsuquyomi/issues/300
augroup typescript
  au!
  autocmd BufNewFile,BufRead *.tsx   set filetype=typescript
  autocmd BufNewFile,BufRead *.tsx   set syntax=typescriptreact
  autocmd BufNewFile,BufRead *.ts   set filetype=typescript
  autocmd BufNewFile,BufRead *.ts   set syntax=javascript
augroup END
