# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/will/.zshrc'

# Setup completion
autoload -Uz compinit
compinit

# fzf completion & keybindings
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
# Trigger fzf completion with ~~<TAB>
FZF_COMPLETION_TRIGGER='~~'
# .gitignore aware file list
FZF_DEFAULT_COMMAND='ag -g ""'
FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install

#### Aliases ####
alias sudo='sudo ' # To allow sudo use with aliases
alias pacman='sudo aura'
alias svim='sudo vim'

alias hibrnte='sudo systemctl hibernate'
alias cp='rsync -avhz --progress'
alias ls='ls --color=always -h'
alias df='df -h'
alias du='du -h'
alias biggest='du -h . | sort -rh | head -$1'
alias battperc='echo "$(date) - $(cat /sys/class/power_supply/BAT*/capacity)% - $(cat /sys/class/power_supply/BAT*/status)"'

# Clipboard manipulation (pipe in / out)
alias cbcopy="xsel -b -i"
alias cbpaste="xsel -b -o"

# Setup screenshots directory and make scrot save to their by default
scrots=~/Pictures/Screenshots
mkdir -p $scrots
alias scrot="scrot '$scrots/%Y-%m-%d_screenshot.png'"

# Base64 encode and decode
function b64d() {
  echo "$1" | base64 -d
}
function b64e() {
  echo "$1" | base64
}
#### Additional Path directories ####
# scripts
export PATH=$PATH:/home/will/scripts
# android sdk
export PATH=$PATH:/opt/android-sdk/tools:/opt/android-sdk/platform-tools
# go-workspace
export GOPATH=$HOME/Projects/go
export PATH=$PATH:$GOPATH/bin

#### ENV VARS ####
# Java blank windows fix
export _JAVA_AWT_WM_NONREPARENTING=1
export CHROME_BIN=$(which chromium)
# So NPM_TOKEN can be used in docker builds
export NPM_TOKEN=$(cat ~/.npmrc | sed  -r -e 's/^\/\/registry.npmjs.org\/:_authToken="?(.*)"?$/\1/;t;d')

# Store the last directory cd'd into so that we can start new shells in the
# same directory.
# Also chmod's it to 600 (rw owner) for a bit of security paranoia
# See xmonad/xmonad.hs for corresponding command to start urxvt
function cd() {
  builtin cd "$@"
  echo $PWD > /tmp/.last_dir_$UID
  chmod 600 /tmp/.last_dir_$UID
}
