---
- name: Install server packages
  pacman:
    state: latest
    name:
      - git
      - docker
      - docker-compose
      - kubectl
      - lm_sensors

- name: Install aur packages
  aur:
    use: makepkg
    state: latest
    name:
      - k3s-bin
  become: yes
  become_user: "{{ user_name }}"

- name: Start docker daemon at boot time
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to the docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes

- name: Enable the k3s service
  systemd:
    name: k3s
    enabled: yes
...
