---
- name: Install pacman.conf
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    owner: root
    group: root

- name: Install ansible (keep it up to date)
  pacman: name=ansible state=latest

- name: Install nice terminal font
  pacman: name=terminus-font state=latest

- name: Globally set up vconsole font and keymap(=us)
  copy: src=vconsole.conf dest=/etc/vconsole.conf

- name: Install sudo
  pacman: name=sudo state=latest

- name: Install polkit
  pacman: name=polkit state=latest

- name: Create sudoers group wheel
  group: name=wheel state=present

- name: Allow wheel group to use wheel
  copy:
    src: 01_wheel_sudoers
    dest: /etc/sudoers.d/01_wheel
    validate: visudo -cf %s
