---
- name: Install preferred packages
  pacman:
    state: latest
    name:
      - tree
      - rsync
      - zip
      - unzip
      - p7zip
      - zsh
      - grml-zsh-config # TODO review what this package is providing.
      - base-devel # For building AUR packages (etc.)
      - lsof
      - dosfstools
      - exfat-utils
      - ntfs-3g
      - gptfdisk # For GPT/MBR management of disks
      - fzf # Fuzzy finder
      - the_silver_searcher # Code searching tool (ag)
      - jq
      - yq

- name: Create user
  user:
    name: "{{ user_name }}"
    shell: /usr/bin/zsh
    groups: wheel
    createhome: yes
    generate_ssh_key: yes
    # Only append groups, don't remove existing ones as others will be
    # added by other roles
    append: yes

- name: Install aura (AUR-enabled pacman wrapper)
  aur:
    name: aura-bin
    use: makepkg
    state: latest
  become: yes
  become_user: "{{ user_name }}"

- name: Install user's zshrc
  copy:
    src: zshrc
    dest: /home/{{ user_name }}/.zshrc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Install user's bashrc
  copy:
    src: bashrc
    dest: /home/{{ user_name }}/.bashrc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Install root's zshrc
  copy:
    src: zshrc
    dest: /root/.zshrc

- name: Ensure root's default shell is zsh
  user:
    name: root
    shell: /usr/bin/zsh
...
