---
- name: Install preferred packages
  pacman:
    state: latest
    name:
      - tree
      - rsync
      - zip
      - unzip
      - zsh
      - grml-zsh-config # TODO review what this package is providing.
      - base-devel # For building AUR packages (etc.)
      - lsof
      - dosfstools
      - exfat-utils
      - ntfs-3g
      - gptfdisk # For GPT/MBR management of disks
      - fzf # Fuzzy finder
      - the_silver_searcher # Code searching tool (ag)
      - jq
      - yq

- name: Create user will
  user:
    name: will
    shell: /usr/bin/zsh
    groups: wheel
    createhome: yes
    generate_ssh_key: yes
    # Only append groups, don't remove existing ones as others will be
    # added by other roles
    append: yes

- name: Install aura (AUR-enabled pacman wrapper)
  aur:
    name: aura-bin
    use: makepkg
    skip_installed: yes
  become: yes
  become_user: will

- name: Install will's zshrc
  copy:
    src: zshrc
    dest: /home/will/.zshrc
    owner: will
    group: will

- name: Install will's bashrc
  copy:
    src: bashrc
    dest: /home/will/.bashrc
    owner: will
    group: will

- name: Install root's zshrc
  copy:
    src: zshrc
    dest: /root/.zshrc

- name: Ensure root's default shell is zsh
  user:
    name: root
    shell: /usr/bin/zsh
...
