---
- name: Update pacman cache
  pacman: update_cache=yes

- name: Install preferred packages
  pacman: name={{ item }} state=latest
  with_items:
    - tree
    - rsync
    - zip
    - unzip
    - zsh
    - grml-zsh-config # TODO review what this package is providing.
    - base-devel # For building AUR packages (etc.)
    - lsof
    - dosfstools
    - exfat-utils
    - ntfs-3g
    - fzf # Fuzzy finder

- name: Create user will
  user:
    name: will
    shell: /usr/bin/zsh
    groups: wheel
    createhome: yes
    generate_ssh_key: yes

- name: Install aura (AUR-enabled pacman wrapper)
  include: aur/pkg.yml pkg_name={{ item }}
  vars:
    makepkg_nonroot_user: will
  with_items:
    - aur-git # For zsh completion of AUR packages
    - aura-bin # Using the precompiled binary, because pacman-Haskell hell.

- name: Install will's zshrc
  copy:
    src: zshrc
    dest: /home/will/.zshrc
    owner: will
    group: will

- name: Install root's zshrc
  copy:
    src: zshrc
    dest: /root/.zshrc

- name: Ensure root's default shell is zsh
  user:
    name: root
    shell: /usr/bin/zsh
...
