---
- name: Install networking packages
  pacman:
    state: latest
    name:
      - openssh
      - easy-rsa
      - gnu-netcat
      - tcpdump
      - traceroute
      - nmap
      - bind-tools # DNS utilities

- name: Install systemd-resolved config
  copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root

- name: Symlink /etc/resolv.conf to dynamic systemd-resolved config
  file:
    state: link
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

