---
- name: Install networking packages
  pacman:
    state: latest
    name:
      - openssh
      - easy-rsa
      - gnu-netcat
      - tcpdump
      - traceroute
      - nmap
      - bind-tools # DNS utilities
      - crda # Wireless regdomain database
      - avahi # mDNS service discovery
      - nss-mdns # Ditto
      - hostapd

- name: Install systemd-resolved config
  copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root

- name: Symlink /etc/resolv.conf to dynamic systemd-resolved config
  file:
    state: link
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Install nss-mdns config
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root

- name: Limit the nss-mdns resolver to .local domains
  copy:
    src: mdns.allow
    dest: /etc/mdns.allow
    owner: root
    group: root

- name: Start & enable the avahi daemon
  systemd:
    name: avahi-daemon
    enabled: yes
    state: started
