---
- name: Install vim
  pacman: name=vim state=latest

- name: Install user's vimrc
  copy:
    src: vimrc
    dest: /home/{{ user_name }}/.vimrc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Create .vim folder and subdirectories
  file:
    path: /home/{{ user_name }}/.vim/{{ item }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  with_items:
    - bundle
    - autoload

- name: Install pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: /home/{{ user_name }}/.vim/autoload/pathogen.vim
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Install plugins from github
  git:
    repo: https://github.com/{{ item.owner }}/{{ item.reponame }}.git
    dest: /home/{{ user_name }}/.vim/bundle/{{ item.reponame }}
  become: yes
  become_user: "{{ user_name }}"
  with_items:
    - owner: dimonomid
      reponame: auto-pairs-gentle
    - owner: Shougo
      reponame: vimproc.vim
    - owner: Quramy
      reponame: tsuquyomi
    - owner: leafgarland
      reponame: typescript-vim
    - owner: briancollins
      reponame: vim-jst
    - owner: ElmCast
      reponame: elm-vim
    - owner: junegunn
      reponame: fzf.vim
    - owner: davidhalter
      reponame: jedi-vim
    - owner: vim-syntastic
      reponame: syntastic
    - owner: prettier
      reponame: vim-prettier

- name: Ensure unused plugins are uninstalled
  file:
    path: /home/{{ user_name }}/.vim/bundle/{{ item }}
    state: absent
  with_items:
    - vim-surround

- name: Make vimproc
  make:
    chdir: /home/{{ user_name }}/.vim/bundle/vimproc.vim
  become: yes
  become_user: "{{ user_name }}"

- name: Install root's vimrc
  copy:
    src: vimrc
    dest: /root/.vimrc
