---
ansible_connection: local
become_method: su

# ACPI Battery name
battery_acpi_name: "BAT0"
# ACPI AC charging info file in /sys/class/power_supply
ac_charging_file: "AC/online"
# Auto-suspend when (not charging and) remaining battery capacity is lteq to
autosuspend_battery_percentage: 5
# Wireless interface (for displaying connected SSID & strength)
wireless_interface: "wlp61s0"
# CPU core temps to monitor
core_temps:
  # core0 seems to be something else
  - core1
  - core2
  - core3
  - core4
...
