---
- name: Install bios cli tools
  pacman:
    name: libsmbios
    state: latest

- name: Install powertop
  pacman:
    name: powertop
    state: latest

- name: Create group for users able to change the backlight brightness
  group:
    name: backlight

- name: Add user to backlight group
  user:
    name: "{{ user_name }}"
    groups: backlight
    append: yes

- name: Install udev rules to set the backlight permissions on boot
  copy:
    src: 99-backlight.rules
    dest: /etc/udev/rules.d/99-backlight.rules
